"use client";
import Link from "next/link";
import { useState } from "react";
import { briefQuestions, exclusionCopyText, exclusions, followUps, normalizeClipboardText, onboardingCopyText, onboardingQuestions, revisionPolicyCopyText, salesKitNav, services, whatsappTemplates, formatRupiah } from "@/config/sales-kit";

function CopyButton({ text, label = "Copy" }: { text: string; label?: string }) { const [state, setState] = useState<"idle" | "done" | "failed">("idle"); const copy = async () => { const value = normalizeClipboardText(text); try { if (!navigator.clipboard?.writeText) throw new Error(); await navigator.clipboard.writeText(value); setState("done"); } catch { try { const area = document.createElement("textarea"); area.value = value; document.body.append(area); area.select(); if (!document.execCommand("copy")) throw new Error(); area.remove(); setState("done"); } catch { setState("failed"); } } window.setTimeout(() => setState("idle"), 2200); }; return <button className="sk-copy" onClick={copy} type="button" aria-label={`${label} ke clipboard`}>{state === "done" ? "Disalin ✓" : state === "failed" ? "Gagal menyalin" : label}</button>; }
const fields = ["Nama brand / organisasi", "Website / Instagram / TikTok", "Produk / jasa", "Target audience", "Apa yang ingin dibuat?", "Sudah punya script/bahan atau baru punya topik?", "Kira-kira berapa video?", "Deadline jika ada", "Referensi yang disukai", "Nomor WhatsApp / contact person", "Apa yang paling penting dari konten ini?"];
const paymentTerms = "Consultation: 100% sebelum sesi.\nOrder/project total < Rp1.000.000: 100% di muka.\nOrder/project total ≥ Rp1.000.000: 50% DP sebelum pengerjaan, 50% sebelum final delivery.";

export function SalesKitWorkspace() {
 const [brief, setBrief] = useState<string[]>(Array(fields.length).fill("")); const [service, setService] = useState("AI Content Factory"); const [quote, setQuote] = useState({ number: "", date: "", valid: "", client: "", brand: "", videos: "1", duration: "", format: "9:16", platform: "", deliverables: "", subtotal: "", additional: "", total: "", notes: "" }); const [invoice, setInvoice] = useState({ number: "", date: "", due: "", client: "", brand: "", description: "", qty: "1", price: "", total: "", status: "", bank: "", account: "", holder: "" });
 const updateQuote = (key: keyof typeof quote, value: string) => setQuote({ ...quote, [key]: value }); const updateInvoice = (key: keyof typeof invoice, value: string) => setInvoice({ ...invoice, [key]: value });
 const briefLabels = ["Nama brand/organisasi", "Website / Social Media", "Produk/Jasa", "Target Audience", "Kebutuhan Konten", "Status Bahan", "Jumlah Video", "Deadline", "Referensi", "Contact Person", "Hal Paling Penting"];
 const briefSummary = `*CLIENT BRIEF*\n\n${briefLabels.map((f, i) => `${f}:\n${brief[i]?.trim() || "-"}`).join("\n\n")}`;
 const quoteText = `*PEMBELAJAR BELAJAR*\n*AI CONTENT FACTORY*\n\n*QUOTATION*\n\nNomor: ${quote.number || "-"}\nTanggal: ${quote.date || "-"}\nBerlaku sampai: ${quote.valid || "-"}\n\n*Kepada*\nNama: ${quote.client || "-"}\nBrand/Organisasi: ${quote.brand || "-"}\n\n*SCOPE PROJECT*\nLayanan: ${service}\nJumlah video: ${quote.videos || "-"}\nEstimasi durasi: ${quote.duration || "-"}\nFormat: ${quote.format || "-"}\nTarget platform: ${quote.platform || "-"}\n\n*DELIVERABLES*\n${quote.deliverables || "-"}\n\n*HARGA*\nSubtotal: ${formatRupiah(quote.subtotal)}\nTambahan scope: ${formatRupiah(quote.additional)}\n*TOTAL: ${formatRupiah(quote.total)}*\n\n*TIMELINE*\nProduksi dimulai setelah brief lengkap, pembayaran sesuai ketentuan, dan materi yang dibutuhkan telah diterima.\n\n*PEMBAYARAN*\n${paymentTerms}\n\n*CATATAN*\nPerubahan scope setelah approval akan dikonfirmasi dan disetujui terlebih dahulu sebelum dikenakan biaya tambahan.\n${quote.notes || ""}`;
 const totalAmount = Number(invoice.total.replace(/\D/g, "")); const hasDp = /dp/i.test(invoice.status);
 const invoiceText = `*PEMBELAJAR BELAJAR*\n\n*INVOICE*\n\nInvoice No: ${invoice.number || "-"}\nTanggal: ${invoice.date || "-"}\nJatuh tempo: ${invoice.due || "-"}\n\n*Ditagihkan kepada*\nNama: ${invoice.client || "-"}\nBrand/Organisasi: ${invoice.brand || "-"}\n\n*RINCIAN*\n${invoice.description || "-"}\nQty: ${invoice.qty || "-"}\nHarga: ${formatRupiah(invoice.price)}\nTotal: ${formatRupiah(invoice.total)}\n\n*TOTAL: ${formatRupiah(invoice.total)}*${hasDp && totalAmount ? `\n\nDP 50%: ${formatRupiah(String(totalAmount / 2))}\nSisa pembayaran: ${formatRupiah(String(totalAmount / 2))}` : ""}\n\n*PEMBAYARAN*\nNama Bank: ${invoice.bank || "-"}\nNomor Rekening: ${invoice.account || "-"}\nAtas Nama: ${invoice.holder || "-"}\n\n${service === "AI Content Consultation" ? "Jadwal dikonfirmasi setelah pembayaran diterima." : "Pengerjaan dimulai setelah pembayaran awal dan materi yang dibutuhkan telah diterima."}`;
 return <main className="sales-kit"><header className="sk-header"><Link href="/" className="sk-brand"><strong>Pembelajar Belajar</strong><span>/ Konten · INTERNAL SALES KIT</span></Link><nav><Link href="/">← Landing Page</Link><Link href="/roadmap">Roadmap →</Link></nav></header><div className="sk-layout"><aside className="sk-nav"><strong>Sales Kit</strong>{salesKitNav.map((x) => <a key={x} href={`#${x.toLowerCase().replaceAll(" ", "-")}`}>{x}</a>)}</aside><div className="sk-content"><section className="sk-hero"><p>AI CONTENT FACTORY · INTERNAL OPERATIONS</p><h1>Sales Kit</h1><p>Semua template yang dibutuhkan dari calon pelanggan pertama kali menghubungi sampai project siap dimulai.</p><small>Halaman internal Pembelajar Belajar.</small><div className="sk-prices">{services.map((s) => <div key={s.id}><strong>{s.name}</strong><span>{s.price}</span></div>)}</div></section><section className="sk-decision"><strong>Calon customer masuk. Pilih jalurnya:</strong><a href="#scope-layanan">Mau bikin sendiri → Consultation</a><a href="#scope-layanan">Sudah punya script/bahan → Production</a><a href="#scope-layanan">Baru punya topik → Factory</a></section><p className="sk-flow">Lead → Client Brief → Tentukan Service → Quotation → Payment → Onboarding → Approval → Production → Revision → Final Delivery → Follow-up</p>
 <Section title="Scope Production vs Factory" id="scope-layanan">{services.map((s) => <article className="sk-service" id={s.id} key={s.id}><div><p>{s.price}</p><h3>{s.name}</h3><p>Untuk: {s.for}</p></div><div><strong>Kita mengerjakan</strong><ul>{s.included.map((i) => <li key={i}>{i}</li>)}</ul><p>{s.output}</p><small>{s.note}</small></div></article>)}<div className="sk-callout">GUIDANCE · Consultation → Anda mengerjakan sendiri. &nbsp; EXECUTION · Production → Anda membawa bahan, kami memproduksi. &nbsp; THINKING + EXECUTION · Factory → Anda membawa topik, kami membantu dari awal sampai final.</div></Section>
 <Section title="Yang Tidak Termasuk Paket Standar" id="yang-tidak-termasuk"><p>Agar scope dan waktu produksi tetap jelas, beberapa kebutuhan berikut tidak termasuk paket standar kecuali disepakati secara terpisah.</p><ul className="sk-list">{exclusions.map((x) => <li key={x}>{x}</li>)}</ul><p><strong>Kami tidak menjamin viral, jumlah views, engagement, leads, atau penjualan tertentu.</strong></p><p>Klien bertanggung jawab memastikan materi, logo, audio, foto, video, dan aset yang diberikan mempunyai hak penggunaan yang sesuai.</p><CopyButton text={exclusionCopyText} label="Copy exclusion list" /></Section>
 <Section title="Aturan Revisi Operasional" id="aturan-revisi"><h3>2 putaran revisi minor tersedia untuk Production dan Factory sesuai workflow.</h3><p><strong>Satu putaran revisi</strong> berarti seluruh feedback dikumpulkan menjadi satu feedback terstruktur, kemudian dikerjakan bersama.</p><p><strong>Minor:</strong> typo, wording pendek, CTA, timing ringan, volume, urutan kecil, koreksi elemen visual tertentu, atau adjustment ringan tanpa mengubah creative direction.</p><p><strong>Mayor / change of scope:</strong> mengganti konsep/script/style/karakter utama, membuat ulang storyboard, menambah scene signifikan, versi dengan arah kreatif berbeda, atau mengubah objective project.</p><p>Perubahan mayor setelah tahap approval dapat memerlukan penyesuaian biaya dan waktu karena sebagian proses produksi perlu dibuat ulang. Penyesuaian akan diinformasikan sebelum pengerjaan dilanjutkan.</p><p>Typo, file rusak, atau hasil yang tidak sesuai dengan materi yang telah disetujui karena kesalahan dari pihak kami tidak dihitung sebagai jatah revisi.</p><CopyButton text={revisionPolicyCopyText} label="Copy revision policy" /></Section>
 <Section title="Client Brief" id="client-brief"><p>Data pada helper ini tidak dikirim ke server.</p><CopyButton text={briefQuestions} label="Copy questions" /><div className="sk-form">{fields.map((f, i) => <label key={f}>{f}<textarea value={brief[i]} onChange={(e) => { const next = [...brief]; next[i] = e.target.value; setBrief(next); }} /></label>)}</div><CopyButton text={briefSummary} label="Copy brief summary" /><button className="sk-clear" type="button" onClick={() => { if (!brief.some(Boolean) || window.confirm("Kosongkan client brief?") ) setBrief(Array(fields.length).fill("")); }}>Clear</button></Section>
 <Section title="Onboarding Form" id="onboarding"><p>Digunakan setelah client deal. Logo/asset dapat dikirim melalui channel project yang disepakati.</p><pre className="sk-template">{onboardingQuestions}</pre><CopyButton text={onboardingCopyText} label="Copy onboarding questions" /></Section>
 <Section title="Quotation Template" id="quotation"><Form fields={[["Nomor", "number"], ["Tanggal", "date"], ["Berlaku sampai", "valid"], ["Nama client", "client"], ["Brand", "brand"], ["Jumlah video", "videos"], ["Estimasi durasi", "duration"], ["Format", "format"], ["Platform", "platform"], ["Deliverables", "deliverables"], ["Subtotal", "subtotal"], ["Tambahan scope", "additional"], ["Total", "total"], ["Notes", "notes"]]} data={quote} update={updateQuote} /><label className="sk-select">Layanan<select value={service} onChange={(e) => setService(e.target.value)}>{services.map((s) => <option key={s.id}>{s.name}</option>)}</select></label><pre className="sk-template">{quoteText}</pre><CopyButton text={quoteText} label="Copy quotation" /></Section>
 <Section title="WhatsApp Templates" id="whatsapp">{whatsappTemplates.map(([title, text]) => <Template key={title} title={title} text={text} />)}<Template title="Send client brief" text={briefQuestions} /><p className="sk-internal-note">Catatan internal: personalisasi minimal dengan nama brand dan satu konteks yang relevan sebelum mengirim.</p></Section>
 <Section title="Follow-up Templates" id="follow-up">{followUps.map(([title, text]) => <Template key={title} title={title} text={text} />)}<p className="sk-internal-note">Catatan internal: tambahkan value baru pada follow-up pertama.</p><p>Setelah follow-up #2: STOP. Jangan mengejar prospek diam tanpa batas.</p></Section>
 <Section title="Invoice Template" id="invoice"><p>Isi detail pembayaran secara manual; tidak ada rekening yang disimpan atau di-hardcode.</p><Form fields={[["Invoice number", "number"], ["Tanggal", "date"], ["Jatuh tempo", "due"], ["Client", "client"], ["Brand", "brand"], ["Deskripsi", "description"], ["Qty", "qty"], ["Unit price", "price"], ["Total", "total"], ["Payment status / DP", "status"], ["Nama bank", "bank"], ["Nomor rekening", "account"], ["Atas nama", "holder"]]} data={invoice} update={updateInvoice} /><pre className="sk-template">{invoiceText}</pre><CopyButton text={invoiceText} label="Copy invoice" /></Section>
 </div></div></main>;
}
function Section({ title, id, children }: { title: string; id: string; children: React.ReactNode }) { return <section className="sk-section" id={id}><h2>{title}</h2>{children}</section>; }
function Template({ title, text }: { title: string; text: string }) { return <article className="sk-block"><h3>{title}</h3><pre className="sk-template">{text}</pre><CopyButton text={text} /></article>; }
function Form({ fields, data, update }: { fields: [string, string][]; data: Record<string, string>; update: (key: never, value: string) => void }) { return <div className="sk-form">{fields.map(([label, key]) => <label key={key}>{label}<input value={data[key] || ""} onChange={(e) => update(key as never, e.target.value)} /></label>)}</div>; }
