"use client";
import Link from "next/link";
import { useState } from "react";
import { briefQuestions, exclusions, followUps, onboardingQuestions, salesKitNav, services, whatsappTemplates } from "@/config/sales-kit";

function CopyButton({ text, label = "Copy" }: { text: string; label?: string }) { const [done, setDone] = useState(false); const copy = async () => { try { await navigator.clipboard.writeText(text); } catch { const area = document.createElement("textarea"); area.value = text; document.body.append(area); area.select(); document.execCommand("copy"); area.remove(); } setDone(true); window.setTimeout(() => setDone(false), 2200); }; return <button className="sk-copy" onClick={copy} type="button" aria-label={`${label} ke clipboard`}>{done ? "Disalin ✓" : label}</button>; }
const fields = ["Nama brand / organisasi", "Website / Instagram / TikTok", "Produk / jasa", "Target audience", "Apa yang ingin dibuat?", "Sudah punya script/bahan atau baru punya topik?", "Kira-kira berapa video?", "Deadline jika ada", "Referensi yang disukai", "Nomor WhatsApp / contact person", "Apa yang paling penting dari konten ini?"];
const paymentTerms = "Consultation: 100% sebelum sesi.\nOrder/project total < Rp1.000.000: 100% di muka.\nOrder/project total ≥ Rp1.000.000: 50% DP sebelum pengerjaan, 50% sebelum final delivery.";

export function SalesKitWorkspace() {
 const [brief, setBrief] = useState<string[]>(Array(fields.length).fill("")); const [service, setService] = useState("AI Content Factory"); const [quote, setQuote] = useState({ number: "", date: "", valid: "", client: "", brand: "", videos: "1", duration: "", format: "9:16", platform: "", deliverables: "", subtotal: "", additional: "", total: "", notes: "" }); const [invoice, setInvoice] = useState({ number: "", date: "", due: "", client: "", brand: "", description: "", qty: "1", price: "", total: "", status: "", bank: "", account: "", holder: "" });
 const updateQuote = (key: keyof typeof quote, value: string) => setQuote({ ...quote, [key]: value }); const updateInvoice = (key: keyof typeof invoice, value: string) => setInvoice({ ...invoice, [key]: value });
 const briefSummary = `CLIENT BRIEF\n${fields.map((f, i) => `${f}: ${brief[i]}`).join("\n")}`;
 const quoteText = `PEMBELAJAR BELAJAR\nAI CONTENT FACTORY\n\nQUOTATION\nNomor: ${quote.number}\nTanggal: ${quote.date}\nBerlaku sampai: ${quote.valid}\n\nKepada\nNama: ${quote.client}\nBrand/Organisasi: ${quote.brand}\n\nSCOPE PROJECT\nLayanan: ${service}\nJumlah video: ${quote.videos}\nEstimasi durasi: ${quote.duration}\nFormat: ${quote.format}\nTarget platform: ${quote.platform}\n\nDELIVERABLES\n${quote.deliverables}\n\nHARGA\nSubtotal: ${quote.subtotal}\nTambahan scope: ${quote.additional}\nTOTAL: ${quote.total}\n\nTIMELINE\nProduksi dimulai setelah brief lengkap, pembayaran sesuai ketentuan, dan materi yang dibutuhkan telah diterima.\n\nPAYMENT\n${paymentTerms}\n\nCATATAN\nPerubahan scope setelah approval akan dikonfirmasi dan disetujui terlebih dahulu sebelum dikenakan biaya tambahan.\n${quote.notes}`;
 const invoiceText = `PEMBELAJAR BELAJAR\n\nINVOICE\nInvoice No: ${invoice.number}\nTanggal: ${invoice.date}\nJatuh tempo: ${invoice.due}\n\nDITAGIHKAN KEPADA\nNama: ${invoice.client}\nBrand/Organisasi: ${invoice.brand}\n\nDeskripsi: ${invoice.description}\nQty: ${invoice.qty}\nHarga: ${invoice.price}\nTOTAL: ${invoice.total}\nStatus pembayaran/DP: ${invoice.status}\n\nPEMBAYARAN\nNama Bank: ${invoice.bank}\nNomor Rekening: ${invoice.account}\nAtas Nama: ${invoice.holder}\n\nPengerjaan dimulai setelah pembayaran awal dan materi yang dibutuhkan telah diterima. Untuk Consultation, jadwal dikonfirmasi setelah pembayaran diterima.`;
 return <main className="sales-kit"><header className="sk-header"><Link href="/" className="sk-brand"><strong>Pembelajar Belajar</strong><span>/ Konten · INTERNAL SALES KIT</span></Link><nav><Link href="/">← Landing Page</Link><Link href="/roadmap">Roadmap →</Link></nav></header><div className="sk-layout"><aside className="sk-nav"><strong>Sales Kit</strong>{salesKitNav.map((x) => <a key={x} href={`#${x.toLowerCase().replaceAll(" ", "-")}`}>{x}</a>)}</aside><div className="sk-content"><section className="sk-hero"><p>AI CONTENT FACTORY · INTERNAL OPERATIONS</p><h1>Sales Kit</h1><p>Semua template yang dibutuhkan dari calon pelanggan pertama kali menghubungi sampai project siap dimulai.</p><small>Halaman internal Pembelajar Belajar.</small><div className="sk-prices">{services.map((s) => <div key={s.id}><strong>{s.name}</strong><span>{s.price}</span></div>)}</div></section><section className="sk-decision"><strong>Calon customer masuk. Pilih jalurnya:</strong><a href="#scope-layanan">Mau bikin sendiri → Consultation</a><a href="#scope-layanan">Sudah punya script/bahan → Production</a><a href="#scope-layanan">Baru punya topik → Factory</a></section><p className="sk-flow">Lead → Client Brief → Tentukan Service → Quotation → Payment → Onboarding → Approval → Production → Revision → Final Delivery → Follow-up</p>
 <Section title="Scope Production vs Factory" id="scope-layanan">{services.map((s) => <article className="sk-service" id={s.id} key={s.id}><div><p>{s.price}</p><h3>{s.name}</h3><p>Untuk: {s.for}</p></div><div><strong>Kita mengerjakan</strong><ul>{s.included.map((i) => <li key={i}>{i}</li>)}</ul><p>{s.output}</p><small>{s.note}</small></div></article>)}<div className="sk-callout">GUIDANCE · Consultation → Anda mengerjakan sendiri. &nbsp; EXECUTION · Production → Anda membawa bahan, kami memproduksi. &nbsp; THINKING + EXECUTION · Factory → Anda membawa topik, kami membantu dari awal sampai final.</div></Section>
 <Section title="Yang Tidak Termasuk Paket Standar" id="yang-tidak-termasuk"><p>Agar scope dan waktu produksi tetap jelas, beberapa kebutuhan berikut tidak termasuk paket standar kecuali disepakati secara terpisah.</p><ul className="sk-list">{exclusions.map((x) => <li key={x}>{x}</li>)}</ul><p><strong>Kami tidak menjamin viral, jumlah views, engagement, leads, atau penjualan tertentu.</strong></p><p>Klien bertanggung jawab memastikan materi, logo, audio, foto, video, dan aset yang diberikan mempunyai hak penggunaan yang sesuai.</p><CopyButton text={exclusions.map((x) => `- ${x}`).join("\n")} label="Copy exclusion list" /></Section>
 <Section title="Aturan Revisi Operasional" id="aturan-revisi"><h3>2 putaran revisi minor tersedia untuk Production dan Factory sesuai workflow.</h3><p><strong>Satu putaran revisi</strong> berarti seluruh feedback dikumpulkan menjadi satu feedback terstruktur, kemudian dikerjakan bersama.</p><p><strong>Minor:</strong> typo, wording pendek, CTA, timing ringan, volume, urutan kecil, koreksi elemen visual tertentu, atau adjustment ringan tanpa mengubah creative direction.</p><p><strong>Mayor / change of scope:</strong> mengganti konsep/script/style/karakter utama, membuat ulang storyboard, menambah scene signifikan, versi dengan arah kreatif berbeda, atau mengubah objective project.</p><p>Perubahan mayor setelah tahap approval dapat memerlukan penyesuaian biaya dan waktu karena sebagian proses produksi perlu dibuat ulang. Penyesuaian akan diinformasikan sebelum pengerjaan dilanjutkan.</p><p>Typo, file rusak, atau hasil yang tidak sesuai dengan materi yang telah disetujui karena kesalahan dari pihak kami tidak dihitung sebagai jatah revisi.</p><CopyButton text="ATURAN REVISI\n2 putaran revisi minor tersedia. Satu putaran berarti seluruh feedback dikumpulkan menjadi satu feedback terstruktur. Perubahan mayor setelah approval dapat memerlukan penyesuaian biaya dan waktu; akan diinformasikan sebelum pengerjaan dilanjutkan. Kesalahan dari pihak kami tidak dihitung sebagai jatah revisi." label="Copy revision policy" /></Section>
 <Section title="Client Brief" id="client-brief"><p>Data pada helper ini tidak dikirim ke server.</p><CopyButton text={briefQuestions} label="Copy questions" /><div className="sk-form">{fields.map((f, i) => <label key={f}>{f}<textarea value={brief[i]} onChange={(e) => { const next = [...brief]; next[i] = e.target.value; setBrief(next); }} /></label>)}</div><CopyButton text={briefSummary} label="Copy brief summary" /><button className="sk-clear" type="button" onClick={() => { if (!brief.some(Boolean) || window.confirm("Kosongkan client brief?") ) setBrief(Array(fields.length).fill("")); }}>Clear</button></Section>
 <Section title="Onboarding Form" id="onboarding"><p>Digunakan setelah client deal. Logo/asset dapat dikirim melalui channel project yang disepakati.</p><pre className="sk-template">{onboardingQuestions}</pre><CopyButton text={onboardingQuestions} label="Copy onboarding questions" /></Section>
 <Section title="Quotation Template" id="quotation"><Form fields={[["Nomor", "number"], ["Tanggal", "date"], ["Berlaku sampai", "valid"], ["Nama client", "client"], ["Brand", "brand"], ["Jumlah video", "videos"], ["Estimasi durasi", "duration"], ["Format", "format"], ["Platform", "platform"], ["Deliverables", "deliverables"], ["Subtotal", "subtotal"], ["Tambahan scope", "additional"], ["Total", "total"], ["Notes", "notes"]]} data={quote} update={updateQuote} /><label className="sk-select">Layanan<select value={service} onChange={(e) => setService(e.target.value)}>{services.map((s) => <option key={s.id}>{s.name}</option>)}</select></label><pre className="sk-template">{quoteText}</pre><CopyButton text={quoteText} label="Copy quotation" /></Section>
 <Section title="WhatsApp Templates" id="whatsapp">{whatsappTemplates.map(([title, text]) => <Template key={title} title={title} text={text} />)}<Template title="Send client brief" text={briefQuestions} /></Section>
 <Section title="Follow-up Templates" id="follow-up">{followUps.map(([title, text]) => <Template key={title} title={title} text={text} />)}<p>Setelah follow-up #2: STOP. Jangan mengejar prospek diam tanpa batas.</p></Section>
 <Section title="Invoice Template" id="invoice"><p>Isi detail pembayaran secara manual; tidak ada rekening yang disimpan atau di-hardcode.</p><Form fields={[["Invoice number", "number"], ["Tanggal", "date"], ["Jatuh tempo", "due"], ["Client", "client"], ["Brand", "brand"], ["Deskripsi", "description"], ["Qty", "qty"], ["Unit price", "price"], ["Total", "total"], ["Payment status / DP", "status"], ["Nama bank", "bank"], ["Nomor rekening", "account"], ["Atas nama", "holder"]]} data={invoice} update={updateInvoice} /><pre className="sk-template">{invoiceText}</pre><CopyButton text={invoiceText} label="Copy invoice" /></Section>
 </div></div></main>;
}
function Section({ title, id, children }: { title: string; id: string; children: React.ReactNode }) { return <section className="sk-section" id={id}><h2>{title}</h2>{children}</section>; }
function Template({ title, text }: { title: string; text: string }) { return <article className="sk-block"><h3>{title}</h3><pre className="sk-template">{text}</pre><CopyButton text={text} /></article>; }
function Form({ fields, data, update }: { fields: [string, string][]; data: Record<string, string>; update: (key: never, value: string) => void }) { return <div className="sk-form">{fields.map(([label, key]) => <label key={key}>{label}<input value={data[key] || ""} onChange={(e) => update(key as never, e.target.value)} /></label>)}</div>; }
